name: akuma
description: Rogue-like dungeon clicker game.
publish_to: 'none'
version: 0.1.0-alpha.1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  badges: ^2.0.3
  bordered_text: ^2.0.0
  collection: ^1.16.0
  decimal: ^2.3.0
  fluent:
    git: https://github.com/sagudev/fluent-dart.git
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.2
  get: ^4.6.5
  google_fonts: ^6.1.0
  hive_flutter: ^1.1.0
  hive: ^2.1.0
  js: ^0.6.4
  media_kit: ^1.1.10+1
  mutex: ^3.0.0
  log_me: ^0.1.2
  novel:
    git: https://github.com/lapuske/novel.git
  page_transition: ^2.0.5
  path_provider: ^2.0.10
  sliding_up_panel2: ^3.2.2
  timezone: ^0.9.0
  universal_io: ^2.0.4
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/background/location/
    - assets/background/misc/
    - assets/background/room/
    - assets/character/
    - assets/font/
    - assets/item/artifact/adventurer/
    - assets/item/artifact/initiate/
    - assets/item/artifact/lucky_dog/
    - assets/item/consumable/
    - assets/item/equipable/
    - assets/item/misc/
    - assets/item/resource/
    - assets/item/skill/
    - assets/item/weapon/
    - assets/l10n/
    - assets/monster/construction/
    - assets/monster/delivery/
    - assets/monster/slime/
    - assets/monster/special/
    - assets/monster/veggies/
    - assets/music/
    - assets/skill/
    - assets/sound/
    - assets/sprite/
    - assets/voice/darknightprincess/
    - assets/voice/intro/
    - assets/voice/Rozzi/
    - assets/voice/sfx/