name: akuma
description: Rogue-like dungeon clicker game.
publish_to: 'none'
version: 0.1.0-alpha.1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  badges: ^2.0.3
  bordered_text: ^2.0.0
  collection: ^1.16.0
  fluent:
    git: https://github.com/sagudev/fluent-dart.git
  flutter:
    sdk: flutter
  flutter_local_notifications: ^10.0.0-dev.18
  get: ^4.6.5
  google_fonts: ^3.0.1
  hive_flutter: ^1.1.0
  hive: ^2.1.0
  js: ^0.6.4
  just_audio_mpv: ^0.1.4
  just_audio_windows: ^0.1.0
  just_audio: ^0.9.28
  mutex: ^3.0.0
  novel:
    # path: ../novel
    git:
      url: https://github.com/SleepySquash/novel.dart.git
      ref: improve-implementation
  page_transition: ^2.0.5
  path_provider: ^2.0.10
  sliding_up_panel2: ^3.2.2
  soundpool: ^2.3.0
  timezone: ^0.8.0
  universal_io: ^2.0.4
  uuid: ^3.0.6
  

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/background/location/
    - assets/background/misc/
    - assets/background/room/
    - assets/character/
    - assets/font/
    - assets/item/artifact/adventurer/
    - assets/item/artifact/initiate/
    - assets/item/artifact/lucky_dog/
    - assets/item/consumable/
    - assets/item/equipable/
    - assets/item/misc/
    - assets/item/resource/
    - assets/item/skill/
    - assets/item/weapon/
    - assets/l10n/
    - assets/monster/slime/
    - assets/monster/special/
    - assets/monster/veggies/
    - assets/music/
    - assets/skill/
    - assets/sound/
    - assets/sprite/
    - assets/voice/darknightprincess/
    - assets/voice/intro/
    - assets/voice/Rozzi/
    - assets/voice/sfx/