name: akuma
description: Rogue-like dungeon clicker game.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  audioplayers: ^1.0.1
  badges: ^2.0.3
  bordered_text: ^2.0.0
  collection: ^1.16.0
  fluent:
    git: https://github.com/sagudev/fluent-dart.git
  flutter:
    sdk: flutter
  flutter_local_notifications: ^10.0.0-dev.18
  get: ^4.6.5
  google_fonts: ^3.0.1
  hive_flutter: ^1.1.0
  hive: ^2.1.0
  js: ^0.6.4
  mutex: ^3.0.0
  novel:
    path: ../novel
    # git:
    #   url: https://github.com/SleepySquash/novel.dart.git
    #   ref: improve-implementation
  path_provider: ^2.0.10
  timezone: ^0.8.0
  universal_io: ^2.0.4
  uuid: ^3.0.6
  

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/background/dungeon/
    - assets/background/location/
    - assets/background/room/
    - assets/character/
    - assets/font/
    - assets/l10n/
    - assets/music/
    - assets/monster/slime/
    - assets/voice/intro/
